<?php

/**
 * @file
 * Contains all hook implementations for this module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function trpcultivate_ecosystem_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Provides the module overview in the help tab.
    case 'help.page.trpcultivate_ecosystem':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';

      $output .= '<p>' . t('This module provides content types, fields and importers focused on surveying ecosystem plants and insects.') . '</p>';

      return $output;

    default:
  }
}

/**
 * Insert terms needed by this module into the default chado instance.
 *
 * Expected but not required to be run by a Tripal Job.
 */
function trpcultivate_ecosystem_install_terms() {
  $config_id = 'trpcultivate_ecosystem_terms';
  $terms_setup = \Drupal::service('tripal_chado.terms_init');
  $terms_setup->installTerms($config_id);
}

/**
 * Import content type collections needed by this module.
 *
 * Expected but not required to be run by a Tripal Job.
 */
function trpcultivate_ecosystem_import_contenttypes() {

  $collections = [
    'trpcultivate_ecosystem',
  ];

  // Import the content types.
  $content_type_setup = \Drupal::service('tripal.tripalentitytype_collection');
  $content_type_setup->install($collections);

  // Import the fields.
  $fields = \Drupal::service('tripal.tripalfield_collection');
  $fields->install($collections);
}
